#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

export EXTRA_COMPONENT_DIRS:=~/Robotics/Weta/vm ~/Robotics/Weta/vm/weta-esp

PROJECT_NAME := weta
SRCDIRS := main platform weta-esp-common weta-common

include $(IDF_PATH)/make/project.mk

