#ifndef ____WVMIOCODES_H__
#define __WVMIOCODES_H__

enum eWvmIoCodes
{
	OP_IO_DIN_CONFIG		= 0,
	OP_IO_DOUT_CONFIG		= 1,
	OP_IO_DIGITAL_CONFIG		= 2,
	OP_IO_PWM_TIMER_CONFIG		= 3,
	OP_IO_PWM_CHANNEL_CONFIG		= 4,
	OP_IO_ADC_CONFIG		= 5,
	OP_IO_ADC_CHANNEL_CONFIG		= 6,
	OP_IO_DAC_CONFIG		= 7,
	OP_IO_SERVO_CONFIG		= 8,
	OP_IO_MOTOR_CONFIG		= 9,
	OP_IO_STEPPER_CONFIG		= 10,
	OP_IO_SHIFTER_CONFIG		= 11,
	OP_IO_MOTOR_SELECT		= 12,
	OP_IO_MOTOR_ON		= 13,
	OP_IO_MOTOR_ONFOR		= 14,
	OP_IO_MOTOR_OFF		= 15,
	OP_IO_MOTOR_THISWAY		= 16,
	OP_IO_MOTOR_THATWAY		= 17,
	OP_IO_MOTOR_RD		= 18,
	OP_IO_MOTOR_SETPOWER		= 19,
	OP_IO_MOTOR_BRAKE		= 20,
	OP_IO_SERVO_SELECT		= 21,
	OP_IO_SERVO_HEADING		= 22,
	OP_IO_SERVO_RIGHT		= 23,
	OP_IO_SERVO_LEFT		= 24,
	OP_IO_TURTLE_FORWARD		= 25,
	OP_IO_TURTLE_BACKWARD		= 26,
	OP_IO_TURTLE_LEFT		= 27,
	OP_IO_TURTLE_RIGHT		= 28,
	OP_IO_TURTLE_PENUP		= 29,
	OP_IO_TURTLE_PENDOWN		= 30,
};

#endif