#ifndef ____WVMMATHCODES_H__
#define __WVMMATHCODES_H__

enum eWvmMathCodes
{
	OP_MATH_RANDOM		= 0,
	OP_MATH_RANDOMXY		= 1,
	OP_MATH_POW		= 2,
	OP_MATH_SQR		= 3,
	OP_MATH_SQRT		= 4,
	OP_MATH_EXP		= 5,
	OP_MATH_SIN		= 6,
	OP_MATH_COS		= 7,
	OP_MATH_TAN		= 8,
	OP_MATH_ASIN		= 9,
	OP_MATH_ACOS		= 10,
	OP_MATH_ATAN		= 11,
	OP_MATH_ATAN2		= 12,
	OP_MATH_SINH		= 13,
	OP_MATH_COSH		= 14,
	OP_MATH_TANH		= 15,
	OP_MATH_HYPOT		= 16,
	OP_MATH_LN		= 17,
	OP_MATH_LOG10		= 18,
	OP_MATH_RND		= 19,
	OP_MATH_TRUNC		= 20,
	OP_MATH_FLOOR		= 21,
	OP_MATH_CEIL		= 22,
	OP_MATH_ISNAN		= 23,
	OP_MATH_ISINF		= 24,
};

#endif