#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

export EXTRA_COMPONENT_DIRS:=~/Robotics/Weta/vm

PROJECT_NAME := weta
SRCDIRS := main include boards include/webserver webserver src



include $(IDF_PATH)/make/project.mk

